<?php

namespace App\Application\Common\PageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TranslateMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranslateMenuRepository extends EntityRepository
{
}