<?php

namespace App\Application\Sonata\MediaBundle\Entity;

use Sonata\MediaBundle\Entity\BaseMedia as BaseMedia;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 */
class Media extends BaseMedia
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * @var \App\Application\Common\PageBundle\Entity\TranslateMedia
     */
    private $translates;

    /**
     * Get id.
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set translate
     *
     * @param array $translates
     * @return Translates
     */
    public function setTranslate($translates)
    {
        $this->translates = $translates;

        return $this;
    }

    /**
     * Get translates
     *
     * @return string
     */
    public function getTranslate()
    {
        return $this->translates;
    }
}
