#home:
#    path: /
#    controller: App\Application\Common\PageBundle\Controller\IndexController::index
#
#page_list:
#    path:      /{page}
#    controller: App\Application\Common\PageBundle\Controller\IndexController::list